blog/urls.py
from django.urls import path, include
from django.contrib.staticfiles.storage import StaticFilesStorage, staticfiles_storage
from django.views.generic.base import RedirectView
from blog import views

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('posts', views.BlogPosts.as_view(), name='blog'),
    path('post-creation', staff_member_required(login_url='login')
        (views.PostCreate.as_view()), name='post-creation'),
    path('<slug:slug>', staff_member_required(login_url='login')
        (views.PostUpdate.as_view()), name='post-update'),
    path('<slug:slug>/remove', staff_member_required(login_url='login')
        (views.PostDelete.as_view()), name='post-delete'),
    path('categories/<category>', views.CategoryList.as_view(), name='category'),
    path('post/<slug:slug>', views.PostDetail.as_view(), name='post-detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='like'),
    path('post/<slug:slug>/comment/<int:pk>/like', views.CommentLike.as_view(),
        name='comment-like'),
    path('post/<slug:slug>/comment/<int:pk>/dislike', views.CommentDislike.as_view(),
        name='comment-dislike'),
    path('post/<slug:slug>/comment/<int:pk>/', views.CommentReply.as_view(),
        name='comment-reply'),
    path('post/<slug:slug>/comment/delete/<int:pk>/', views.CommentDelete.as_view(),
        name='comment-delete'),
    ]

leannes_learners/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.socialaccount.models import SocialToken, SocialAccount, SocialApp
from allauth.account.models import EmailAddress
from django.contrib.sites.models import Site
from django_summernote.utils import get_attachment_model

from leannes_learners import views
from django.conf.urls import handler400, handler404, handler403, handler500


admin.site.unregister(SocialToken)
admin.site.unregister(SocialAccount)
admin.site.unregister(SocialApp)
admin.site.unregister(Site)
admin.site.unregister(EmailAddress)
admin.site.unregister(get_attachment_model())

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("django.contrib.auth.urls")),
    path("members/", include("users.urls"), name="users_urls"),
    path("", include("leannes_learners_data.urls"), name="leannes_learners_data_urls"),
    path("blog/", include("blog.urls"), name="blog_urls"),
    path("django_summernote/", include("django_summernote.urls")),
]

handler400 = "leannes_learners.views.bad_request_error_400"
handler403 = "leannes_learners.views.forbidden_error_403"
handler404 = "leannes_learners.views.page_not_found_view_404"
handler500 = "leannes_learners.views.internal_error_500"

templates/django_summernote/urls.py
from django.urls import path

from django_summernote.utils import get_config
from django_summernote.views import (
    SummernoteEditor, SummernoteUploadAttachment
)


urlpatterns = [
    path('editor/<id>/', SummernoteEditor.as_view(),
         name='django_summernote-editor'),
]

if not get_config()['disable_attachment']:
    urlpatterns += [
        path('upload_attachment/', SummernoteUploadAttachment.as_view(),
             name='django_summernote-upload_attachment'),
    ]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.safestring import mark_safe
from users.models import UserProfile
from autoslug import AutoSlugField

# Create your models here.
STATUS = ((0, "Draft"), (1, "Published"))


class Category(models.Model):
    """
    A model for the categories of the dataset.
    """

    title = models.CharField(max_length=50)
    slug = AutoSlugField(max_length=60, populate_from="title", unique=True)

    class Meta:
        ordering = ["title"]
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        """
        returns the title of the category
        """
        return self.title

    def __str__(self):
        """
        Return the name of the object.
        """
        return self.slug


class Post(models.Model):
    """
    The Post model for the blog.
    This is the model that will be used to store the blog posts.
    """

    title = models.CharField(max_length=200, unique=True)
    slug = AutoSlugField(max_length=250, populate_from="title", unique=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={"is_staff": True},
        related_name="post_posts",
    )
    featured_image = CloudinaryField(
        folder="leannes_learners/blog_images/",
        transformation={
            "width": "400",
            "height": "300",
            "crop": "fill",
            "gravity": "face",
            "zoom": "0.5",
        },
        default="image/upload/leannes_learners/default_image/placeholder",
    )
    alt_tag = models.CharField(
        max_length=200, blank=True, verbose_name="image alternative text"
    )
    excerpt = models.TextField(
        blank=False,
        verbose_name="Eye Catching Excerpt - make someone want to read the article",
    )

    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    content = models.TextField(
        verbose_name="Post Content",
        blank=False,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="blogPost_like", blank=True)

    def image_thumb(self):
        """
        Create a thumbnail for the image.
        """
        return mark_safe(
            '<img src="{}" width="100" height="auto">'.format(self.featured_image.url)
        )

    image_thumb.short_discription = "image"
    featured_image.allow_tags = True

    class Meta:
        ordering = ["-updated_at"]
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        """
        returns the title of the post
        """
        return self.title

    def __str__(self):
        """
        Return the slug of the object.
        """
        return self.slug

    def number_of_likes(self):
        """
        Return the number of likes for a post.
        """
        return self.likes.count()

    def get_absolute_url(self):
        """
        Get the absolute url for the post.
        """
        return "post/{}".format(self.slug)


class Comment(models.Model):
    """
    A class for the comments.
    """

    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    liked = models.ManyToManyField(User, blank=True, related_name="comments_liked")
    disliked = models.ManyToManyField(
        User, blank=True, related_name="comments_disliked"
    )
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, blank=True, null=True, related_name="+"
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

    class Meta:
        ordering = ["created_at"]
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        """
        Return a string representation of the comment.
        """
        return f"Comment {self.comment} by {self.name}"

    def number_of_comment_likes(self):
        """
        returns the number of likes for the comment
        """
        return self.liked.count()

    def number_of_comment_dislikes(self):
        """
        returns the number of likes for the comment
        """
        return self.disliked.count()

    @property
    def children(self):
        """
        returns child comments of a parent by created time
        """
        return Comment.objects.filter(parent=self).order_by("-created_at").all()

    @property
    def is_parent(self):
        """
        Check to see if the comment is a parent comment and return true
        """
        if self.parent is None:
            return True
        return False

blog/forms.py
from .models import Comment, Post
from django import forms
from django_summernote.widgets import SummernoteWidget


class CommentForm(forms.ModelForm):
    """
    The comment form for the comment section of the website.
    """

    class Meta:
        model = Comment
        fields = ("comment",)


class CreateNewPostForm(forms.ModelForm):
    """
    Create a form for creating a new post. 
    This is used in the admin site.
    """

    class Meta:
        model = Post
        fields = (
            "title",
            "featured_image",
            "alt_tag",
            "content",
            "excerpt",
            "author",
            "category",
        )
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "alt_tag": forms.TextInput(attrs={"class": "form-control"}),
            "excerpt": forms.Textarea(attrs={"class": "form-control"}),
            "content": SummernoteWidget(attrs={"class": "form-control"}),
            "author": forms.Select(attrs={"class": "form-control"}),
            "category": forms.Select(attrs={"class": "form-control"}),
        }

blog/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin

from django.views import generic, View
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)
from django.db.models import Count

from blog.models import Category, Post, Comment
from .forms import CommentForm, CreateNewPostForm

# Create your views here.


class PostDetail(View):
    def get(self, request, slug, *args, **kwargs):
        """
        Get the data for a specific post.
        """
        queryset = Post.objects
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.order_by("-created_at")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "pages/blog/post.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm(),
            },
        )

    def post(self, request, slug, *args, **kwargs):
        """
        Render the post page.
        """
        queryset = Post.objects
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.order_by("-created_at")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.name = request.user
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            comment_form = CommentForm()
            return HttpResponseRedirect(request.path)
        else:
            comment_form = CommentForm()

        return render(
            request,
            "pages/blog/post.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "comment_form": comment_form,
                "liked": liked,
            },
        )


class BlogPosts(generic.ListView):
    """
    The blog page. This is a generic list view that 
    displays all the posts in the database.
    """

    model = Post
    queryset = Post.objects.order_by("-created_at")
    template_name = "pages/blog/blog.html"
    paginate_by = 9


class CategoryList(ListView):
    """
    The category list view.
    """
    model = Category
    template_name = "pages/blog/category.html"
    context_object_name = "categorylist"

    def get_queryset(self):
        """
        Get the queryset for the category page.
        """
        content = {
            "cat": self.kwargs["category"],
            "posts": Post.objects.filter(
                category__slug=self.kwargs["category"]
            ).filter(),
            "title": self.kwargs["category"].replace("-", " "),
        }
        return content


def category_list(request):
    """
    Return the category list for the category list page.
    """
    category_list = (
        Category.objects.annotate(post_count=Count("post"))
        .filter(post_count__gt=0)
        .order_by("-post_count")
    )
    context = {"category_list": category_list}
    return context


class CommentDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Test function for the test function.
    @returns True if the user is the author of the comment
    or if the user is a member of staff.
    """
    model = Comment
    template_name = "pages/blog/post-comment-delete.html"

    def get_success_url(self):
        """
        Get the success url for the post detail view.
        """
        slug = self.kwargs["slug"]
        return reverse_lazy("post-detail", args=[slug])

    def test_func(self):
        """
        Check if the user is a staff member. 
        If so, return true. Otherwise, return false.
        """
        comment = self.get_object()
        if self.request.user.is_staff:
            return self.request.user.is_staff
        else:
            return self.request.user == comment.name


class CommentDislike(View):
    """
    This function is used to like or dislike a comment.
    It is called when the user clicks on the like or dislike button.
    """
    def post(self, request, slug, pk, *args, **kwargs):
        comment = Comment.objects.get(pk=pk)
        if comment.disliked.filter(id=request.user.id).exists():
            comment.disliked.remove(request.user)
        else:
            comment.disliked.add(request.user)
            if comment.liked.filter(id=request.user.id).exists():
                comment.liked.remove(request.user)
        return HttpResponseRedirect(reverse("post-detail", args=[slug]))


class CommentLike(View):
    """
    This function is used to like or dislike a comment.
    It is called when a user clicks on the like button.
    """
    def post(self, request, slug, pk, *args, **kwargs):
        comment = Comment.objects.get(pk=pk)
        if comment.liked.filter(id=request.user.id).exists():
            comment.liked.remove(request.user)
        else:
            comment.liked.add(request.user)
            if comment.disliked.filter(id=request.user.id).exists():
                comment.disliked.remove(request.user)
        return HttpResponseRedirect(reverse("post-detail", args=[slug]))


class CommentReply(LoginRequiredMixin, View):
    def post(self, request, slug, pk, *args, **kwargs):
        """
        This function is used to post a comment on a post.
        It takes the request, the slug of the post,
        the primary key of the comment, and the comment form.
        """
        post = Post.objects.get(slug=slug)
        parent_comment = Comment.objects.get(pk=pk)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment_form.instance.name = request.user
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.parent = parent_comment
            comment.save()
            comment_form = CommentForm()
            return HttpResponseRedirect(reverse("post-detail", args=[slug]))
        else:
            comment_form = CommentForm()

        return HttpResponseRedirect(reverse("post-detail", args=[slug]))


class PostCreate(CreateView):
    """
    The view for creating a new post.
    """
    model = Post
    template_name = "pages/blog/post-creation.html"
    form_class = CreateNewPostForm


class PostDelete(DeleteView):
    """
    Delete a post from the database.
    """
    model = Post
    template_name = "pages/blog/post-entry-delete.html"
    success_url = reverse_lazy("blog")


class PostLike(View):
    def post(self, request, slug, *args, **kwargs):
        """
        When a user likes a post,
        we want to add them to the likes list of the post.
        """
        post = get_object_or_404(Post, slug=slug)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse("post-detail", args=[slug]))


class PostUpdate(UpdateView):
    """
    The view for editing a post.
    """
    model = Post
    template_name = "pages/blog/post-entry-edit.html"
    form_class = CreateNewPostForm

templates/components/blog/blog-post-card.html
<div class="card-body">
	<div class="image-container">
		<a href="{% url 'blog-post' post.slug %}" class="blog-post-link">
			{% if "placeholder" in post.featured_image.url %}

			<img class="card-img-top"
				src="https://res.cloudinary.com/dkitley1975/image/upload/v1640952840/leannes_learners/default_image/Leannes-Learners-Placeholder-Image.jpg"
				alt="missing image placeholder image">
			{% else %}
			<img class="card-img-top blog-post-link" src=" {{ post.featured_image.url }}" alt="{{ post.alt_tag }}">
			{% endif %}
		</a>

		<div class="image-flash">
			<p class="author text-muted">Author: {{ post.author }}</p>
		</div>
	</div>
	<a href="{% url 'blog-post' post.slug %}" class="blog-post-link">
		<h2 class="card-title text-uppercase">{{ post.title }}</h2>
		<p class="card-text">{{ post.excerpt }}</p>
	</a>
	<hr />
	<p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
		{{ post.number_of_likes }}</p>
</div>

templates/components/blog/comment-modal.html
<!-- Comment-modal.html -->
<div class="d-flex flex-row justify-content-end"></div>
<div class="row">

	<h2 class="text-left">Comments:

		<!-- Button trigger Comment Modal (comment-modal)-->
		<button type="button" class="btn btn-primary mb-1" data-bs-toggle="modal" data-bs-target="#leaveACommentModal">
			<i class="far fa-comment-dots fa-hover" aria-hidden="true"
				title="Click to leave a comment"> </i> Leave a comment
		</button></h2>
</div>
<!-- Comment Modal (comment-modal)-->
<div class="modal fade" id="leaveACommentModal" tabindex="-1" aria-labelledby="leaveACommentModalLabel"
	aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title" id="leaveACommentModalLabel">Leave a comment:</h3>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				{% load crispy_forms_tags %}
				<div class="card-body">
					{% if user.is_authenticated %}
					<p>Posting as: {{ user.username }}</p>
					<form method="post" style="margin-top: 1.3em;">
						{% csrf_token %}
						<div id="div_id_comment" class="form-group"> <label for="id_comment" class=" requiredField">
								Your comment</label>
							<div> <textarea name="comment" cols="40" rows="10" class="textarea form-control" required=""
									id="id_comment"></textarea> </div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-signup">Submit</button>
						</div>
					</form>
					{% else %}
					<p>Thank you for showing an interest and wanting to show your appreciation/or not of the posters
						comments,</p>
					<p class="mt-1">To do so, first please login to your account or register to join our community</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END of Comment Modal (comment-modal)-->
<!-- END of Comment-modal.html -->

templates/components/blog/comment-reply-modal.html
<!-- Comment-reply-modal.html -->
<!-- Button trigger Comment Reply Modal -->
<button type="button" class="btn" data-bs-toggle="modal"
	data-bs-target="#commentReplyModal{{ comment.id }}" name='parent_id'
	value="{{ comment.id }}">
	<i class="far fa-comment-dots fa-hover"
		title="Click to leave a comment"></i></button>
<!-- Comment Reply Modal -->
<div class="modal fade" id="commentReplyModal{{ comment.id }}" tabindex="-1"
	aria-labelledby="commentReplyModalLabel{{ comment.id }}" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title"
					id="commentReplyModalLabel{{ comment.id }}">Reply to Comment
				</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal"
					aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="card-body">
					{% if user.is_authenticated %}
					<p>Posting as: {{ user.username }}</p>
					<form method="post"
						action="{% url 'comment-reply' post.slug comment.pk %}">
						{% csrf_token %}
						<div id="div_id_comment{{ comment.id }}"
							class="form-group"> <label
								for="id_comment{{ comment.id }}"
								class="requiredField">
								Your comment</label>
							<div> <textarea name="comment" cols="40" rows="10"
									class="textarea form-control" required=""
									id="id_comment{{ comment.id }}"></textarea>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary"
								data-bs-dismiss="modal">Close</button>
							<button type="submit"
								class="btn btn-signup">Submit</button>
						</div>
					</form>
					{% else %}
					<p>Thank you for showing an interest and wanting to show
						your appreciation/or not of the posters
						comments,</p>
					<p class="mt-1">To do so, first please login to your account
						or register to join our community</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END of Comment Reply Modal -->
<!-- END of Comment-reply-modal.html -->

templates/components/blog/comments-child-likes.html
<!-- Comment-child-likes.html -->
<div class="d-flex flex-row justify-content-end">
	{% if user.is_authenticated %}
	<form class="text-end" method="POST"
		action="{% url 'comment-dislike' post.slug child_comment.pk %}">
		{% csrf_token %}
		<input type="hidden" name="next" value="{{ request.path }}">
		<button class="btn" type="submit">
			<i class="fa-hover fas fa-thumbs-down icon-color-quaternary"
				title="click to dislike this Comment">
				<span>{{ child_comment.disliked.all.count }}</span></i>
		</button>
	</form>
	<form class="text-end" method="POST"
		action="{% url 'comment-like' post.slug child_comment.pk %}">
		{% csrf_token %}
		<input type="hidden" name="next" value="{{ request.path }}">
		<button class="btn" type="submit">
			<i class="fa-hover fas fa-thumbs-up icon-color-tertiary"
				title="click to like this Comment">
				<span>{{ child_comment.liked.all.count }}</span></i>
		</button>
	</form>
	{% else %}
	{% include "components/blog/comments-likes-child-register-to-like-modal.html" %}
	{% endif %}
</div>
<!-- END of Comment-child-likes.html -->

templates/components/blog/comments-likes-child-register-to-like-modal.html
<!-- Comments-likes-child-register-to-like-modal.html -->
<!-- Button trigger Modal Child Likes - (register) -->
<div>
	<button type="button" class="btn" data-bs-toggle="modal"
		data-bs-target="#likeModal_{{ child_comment.pk }}">
		<i class="fa-hover fas fa-thumbs-down icon-color-quaternary"
			title="please login and click to dislike this Comment">
			<span>{{ child_comment.disliked.all.count }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></i>
		<i class="fa-hover fas fa-thumbs-up icon-color-tertiary"
			title="please login and click to like this Comment">
			<span>{{ child_comment.liked.all.count }}</span></i>
	</button>
</div>
<!-- Modal Child Likes - (register) -->
<div class="modal fade" id="likeModal_{{ child_comment.pk }}" tabindex="-1"
	aria-labelledby="likeModalLabel_{{ child_comment.pk }}" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title"
					id="likeModalLabel_{{ child_comment.pk }}">Show your
					appreciation:</h3>
				<button type="button" class="btn-close" data-bs-dismiss="modal"
					aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p class="mt-4 mb-2 fw-bolder">Thank you for showing an interest
					and wanting to show your
					appreciation/or not of the posters comments,</p>
				<p>Thank you for showing an interest and wanting to show your
					appreciation/or not of the posters
					comments,</p>
				<p class="mt-1">To do so, first please login to your account or
					register to join our community</p>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary"
						data-bs-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End of Comments-likes-child-register-to-like-modal.html -->

templates/components/blog/comments-likes-parent-register-to-like-modal.html
<!-- Comments-likes-parent-register-to-like-modal.html -->
<!-- Button trigger Modal Parent Likes - (register) -->
<div>
	<button type="button" class="btn" data-bs-toggle="modal"
		data-bs-target="#likeModal_{{ comment.pk }}">
		<i class="fa-hover fas fa-thumbs-down icon-color-quaternary"
			title="please login and click to dislike this Comment">
			<span>{{ comment.number_of_comment_dislikes }}&nbsp;&nbsp;&nbsp;&nbsp;</span></i>
		<i class="fa-hover fas fa-thumbs-up icon-color-tertiary"
			title="please login and click to like this Comment">
			<span>{{ comment.number_of_comment_likes  }}&nbsp;</span></i></button>
	{% include "components/blog/comment-reply-modal.html" %}
</div>
<!-- Modal Parent Likes - (register) -->
<div class="modal fade" id="likeModal_{{ comment.pk }}" tabindex="-1"
	aria-labelledby="likeModalLabel_{{ comment.pk }}" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title" id="likeModalLabel_{{ comment.pk }}">
					Show
					your appreciation:</h3>
				<button type="button" class="btn-close" data-bs-dismiss="modal"
					aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<p>Thank you for showing an interest and wanting to show
					your appreciation/or not of the posters
					comments,</p>
				<p class="mt-1">To do so, first please login to your account
					or register to join our community</p>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary"
						data-bs-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END of Comments-likes-parent-register-to-like-modal.html -->

templates/components/blog/comments-parent-likes.html
<!-- Comments-parent-likes.html -->
<div class="d-flex flex-row justify-content-end">
	{% if user.is_authenticated %}
	{% include "components/blog/comment-reply-modal.html" %}
	<form class="text-end" method="POST"
		action="{% url 'comment-dislike' post.slug comment.pk %}">
		{% csrf_token %}
		<input type="hidden" name="next" value="{{ request.path }}">
		<button class="btn" type="submit">
			<i class="fa-hover fas fa-thumbs-down icon-color-quaternary"
				title="click to dislike this Comment">
				<span>{{ comment.number_of_comment_dislikes }}</span></i>
		</button>
	</form>
	<form class="text-end" method="POST"
		action="{% url 'comment-like' post.slug comment.pk %}">
		{% csrf_token %}
		<input type="hidden" name="next" value="{{ request.path }}">
		<button class="btn" type="submit">
			<i class="fa-hover fas fa-thumbs-up icon-color-tertiary"
				title="click to like this Comment">
				<span>{{ comment.number_of_comment_likes }}</span></i>
		</button>
	</form>
	{% else %}
	{% include "components/blog/comments-likes-parent-register-to-like-modal.html" %}
	{% endif %}
</div>
<!-- END of Comments-parent-likes.html -->

templates/components/blog/post-preview-card.html
<!-- post-preview-card.html -->
<div class="col-12 mt-3 left">
	<div class="row">
		{% for post in post_list %}
		<div class="col-md-4">
			<div class="card bg-white img-radius-10 mb-4">
				<div class="card-body">
					<div class="image-container">
						<a href="{% url 'post-detail' post.slug %}"
							class="post-detail-link">
							{% if "placeholder" in post.featured_image.url %}
							<img class="card-img-top img-radius-10 trans-white-background-80"
								src="https://res.cloudinary.com/dkitley1975/image/upload/v1640952840/leannes_learners/default_image/Leannes-Learners-Placeholder-Image.jpg">
							{% else %}
							<img class="card-img-top img-radius-10 trans-white-background-80"
								src=" {{ post.featured_image.url }}"
								alt="{{ post.alt_tag }}">
							{% endif %}
						</a>
						<div class="image-flash">
							<p class="author text-muted">Author:
								{{ post.author.first_name }}
								{{ post.author.last_name }}</p>
						</div>
					</div>
					<a href="{% url 'post-detail' post.slug %}"
						class="post-detail-link">
						<h2 class="card-title text-uppercase">{{ post.title }}
						</h2>
						<p class="card-text">{{ post.excerpt }}</p>
						<p class="author">Read More...</p>
					</a>
					<hr />
					<p class="card-text text-muted h6">
						{{ post.created_at | date:"d F Y" }}
						{% if post.number_of_likes %}
						<i class="fas fa-heart icon-color-quaternary"></i>
						{% else %}
						<i class="far fa-heart icon-color-quaternary"></i>
						{% endif %}
						{{ post.number_of_likes }}
					</p>
				</div>
			</div>
		</div>
		{% if forloop.counter|divisibleby:3 %}
	</div>
	{% endif %}
	{% endfor %}
</div>
<!-- END of post-preview-card.html -->